tsa_webmaster/views.py
from flask import render_template, Blueprint, redirect, url_for
from flask_login import login_user, logout_user, current_user, login_required
from tsa_webmaster import db
from tsa_webmaster.models import Resources, User, ResourceAttendees
from tsa_webmaster.forms import ResourceForm, RegisterForm, LoginForm
from sqlalchemy import select
from datetime import datetime, timezone

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@views.route('/from<string:indexmessage>', methods=['GET', 'POST'])
def index(page = 1, indexmessage = "None"):
    resources = db.paginate(select(Resources).order_by(Resources.created_date.desc()), page=1, per_page=9)
    return render_template('index.html', resources=resources, indexmessage=indexmessage)

@views.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('views.login', loginmessage = "register"))
    return render_template('register.html', form=form)

@views.route('/login', methods=['GET', 'POST'])
@views.route('/login/<string:loginmessage>', methods=['GET', 'POST'])
def login(loginmessage = "None"):
    
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.execute(select(User).filter_by(email=form.email.data)).scalar_one_or_none()
        if user and user.check_password(form.password.data):
            login_user(user)
            return redirect(url_for('views.index', indexmessage = "login"))
        else:
            return render_template('login.html', form=form, loginmessage = 'invalid')
    return render_template('login.html', form=form, loginmessage=loginmessage)

@login_required
@views.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('views.index', indexmessage = 'logout'))

@login_required
@views.route('/submit-resource', methods=['GET', 'POST'])
def submit_resource():
    if current_user.is_authenticated:
        form = ResourceForm()

        if form.validate_on_submit():
            if form.resource_category.data == 'volunteering':
                resource_category = 'Volunteering'
                resource_tags = ", ".join(form.resource_volunteering_tags.data)
            elif form.resource_category.data == 'education':
                resource_category = 'Education'
                resource_tags = ", ".join(form.resource_education_tags.data)
            elif form.resource_category.data == 'recreation':
                resource_category = 'Recreation'
                resource_tags = ", ".join(form.resource_recreation_tags.data)
            else:
                resource_category = 'Miscellaneous'
                resource_tags = "None"
            resource = Resources(
                created_date=datetime.now(timezone.utc),
                user_id=current_user.id,
                resource_title=form.resource_title.data,
                resource_description=form.resource_description.data,
                resource_date = form.resource_date.data,
                resource_time=form.resource_time.data,
                resource_location=form.resource_location.data, 
                resource_category=resource_category,
                resource_tags=resource_tags)

            db.session.add(resource)
            db.session.commit()
            return redirect(url_for('views.index', indexmessage = "submit"))

        return render_template('submit.html', form=form)

    else:
        return redirect(url_for('views.login', loginmessage = "submit"))


@views.route('/resource/<int:resource_id>')
@views.route('/resource/<int:resource_id>/<string:resourcemessage>', methods=['GET', 'POST'])
def resource(resource_id, resourcemessage = "None"):
    resource = db.session.execute(select(Resources).filter_by(id = resource_id)).scalar_one_or_none()
    if resource:
        if resource.attendees and db.session.execute(select(ResourceAttendees).filter_by(resource_id = resource_id, user_id = current_user.id)).scalar_one_or_none():
            is_attending = True
        else:
            is_attending = False

        return render_template('resource.html', resource=resource, resourcemessage=resourcemessage, is_attending=is_attending)
    else:
        return redirect(url_for('views.index', indexmessage = 'resource'))

@login_required
@views.route('/account/<int:current_user_id>')
def account(current_user_id):
    user = db.session.execute(select(User).filter_by(id=current_user_id)).scalar_one_or_none()
    if user:
        return render_template('account.html', user=user)
    else:
        return redirect(url_for('views.index', indexmessage = 'account'))

@views.route('/about')
def about():
    return render_template('about.html')

@login_required
@views.route('/delete/<int:resource_id>')
def delete(resource_id):
    resource = db.session.execute(select(Resources).filter_by(id = resource_id)).scalar_one_or_none()
    if resource and resource.user_id == current_user.id:
        db.session.delete(resource)
        db.session.commit()
        return redirect(url_for('views.index', indexmessage = 'delete'))
    else:
        return redirect(url_for('views.resource', resource_id=resource_id, resourcemessage = 'delete'))

@login_required
@views.route('/attend/<int:resource_id>')
def attend(resource_id):
    if current_user.is_authenticated:
        resource = db.session.scalar(select(Resources).filter_by(id = resource_id))
        if resource:
            if resource.user_id != current_user.id:
                if current_user.id not in resource.attendees:
                    db.session.add(ResourceAttendees(resource_id = resource_id, user_id = current_user.id))
                    db.session.commit()
                    return redirect(url_for('views.resource', resource_id = resource_id, resourcemessage = 'attend'))
                else:
                    return redirect(url_for('views.resource', resource_id = resource_id, resourcemessage = 'already_attending'))
            else:
                return redirect(url_for('views.resource', resource_id = resource_id, resourcemessage = 'already_created'))
        else:
            return redirect(url_for('views.index', resource_id = resource_id, indexmessage = 'resource'))
    else:
        return redirect(url_for('views.login', loginmessage = 'attend'))

@login_required
@views.route('/unattend/<int:resource_id>')
def unattend(resource_id):
    if current_user.is_authenticated:
        resource = db.session.scalar(select(Resources).filter_by(id = resource_id))
        if resource:
            if resource.user_id != current_user.id:
                user = db.session.scalar(select(ResourceAttendees).filter_by(resource_id = resource_id, user_id = current_user.id))
                if user:
                    db.session.delete(user)
                    db.session.commit()
                    return redirect(url_for('views.resource', resource_id = resource_id, resourcemessage = 'unattend'))
                else:
                    return redirect(url_for('views.resource', resource_id = resource_id, resourcemessage = 'not_attending'))
            else:
                return redirect(url_for('views.resource', resource_id = resource_id, resourcemessage = 'already_created'))
        else:
            return redirect(url_for('views.index', indexmessage = 'resource'))
    else:
        return redirect(url_for('views.login', loginmessage = 'unattend'))

tsa_webmaster/templates/Reference Page.html
1. One (1) web page on the site must list all sources
of information used to create the website and be
labeled 'Reference Page.'

2. If copyrighted material, such as text, images, or
sound from other sources is used, proper written
permission must be included/documented on the
reference page.

3. Participants must include a completed Student
Copyright Checklist (in PDF format) as a link on the
website reference page. (See Forms Appendix).
Failure to include a Student Copyright Checklist
will result in a disqualification.

4. Participants must include a completed Work Log
(in PDF format) as a link on the website reference
page. (See Forms Appendix); pages as needed

tsa_webmaster/templates/about.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-4 p-5 bg-primary text-dark rounded">
    <h1>About</h1>
    <p>We are the greatest TSA team!!!!!! We are the greatest!</p>
</div>

{% endblock %}

tsa_webmaster/templates/account.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4 p-5 bg-primary text-dark rounded">
  <h1>Profile</h1>
  <div class = "row">
    <div class = "col-9">
      <img src = "https://futureoflife.org/wp-content/uploads/2020/08/elon_musk_royal_society.jpg" class="card-img-top rounded-circle" width = "500" height = "500">
    </div>
    <div class = "col">
      <h3>Your Account</h3>
      <figure>
        <blockquote class="blockquote">
          <p>8 hours</p>
        </blockquote>
        <figcaption class="blockquote-footer">
          Spent volunteering
        </figcaption>
      </figure>
            <figure>
        <blockquote class="blockquote">
          <p>4 hours</p>
        </blockquote>
        <figcaption class="blockquote-footer">
          Spent teaching
        </figcaption>
      </figure>
            <figure>
        <blockquote class="blockquote">
          <p>12 hours</p>
        </blockquote>
        <figcaption class="blockquote-footer">
          Spent learning
        </figcaption>
      </figure>
    </div>
  </div>
</div>
{% endblock %}

tsa_webmaster/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Community Resource Hub</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="format-detection" content="telephone=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="author" content="AnishVDev">
  <meta name="keywords" content="">

  <!--Bootstrap CSS -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

  <!--vendor css -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/vendor.css') }}">

  <!-- Swiper -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
  <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js" defer></script>

  <!-- jQuery (Required for Slick) -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" defer></script>

  <!-- Slick -->
  <link rel="stylesheet" type="text/css"
    href="https://cdn.jsdelivr.net/npm/slick-carousel/slick/slick.css" />
  <link rel="stylesheet" type="text/css"
    href="https://cdn.jsdelivr.net/npm/slick-carousel/slick/slick-theme.css" />
  <script src="https://cdn.jsdelivr.net/npm/slick-carousel/slick/slick.min.js" defer></script>

  <!-- FontAwesome -->
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Syne:wght@400;600;700;800&display=swap"
    rel="stylesheet">

  <!-- Style Sheet -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
  <!-- IMPORTANT: body padding-top is handled by CSS (so sub-header isn't hidden under fixed header) -->

  <header id="header">
    <!-- Primary Header (fixed) -->
    <nav id="primary-header" class="navbar navbar-expand-lg">
      <div class="container d-flex align-items-center justify-content-between">
        <!-- LEFT SIDE: Logo + Title -->
        <div class="d-flex align-items-center">
          <a class="navbar-brand d-flex align-items-center" href="{{ url_for('views.index') }}">
            <img src="{{ url_for('static', filename='images/logo-transparentbg.png') }}" class="logo img-fluid" alt="Community Resource Hub">
            <span class="navbar-title ms-2">Community Resource Hub</span>
          </a>
        </div>
      
        <!-- RIGHT SIDE: Nav links -->
        <div class="d-flex align-items-center">
          <!-- Navbar toggler for small screens -->
          <button class="navbar-toggler border-0 d-flex d-lg-none" type="button" data-bs-toggle="offcanvas"
            data-bs-target="#bdNavbar" aria-controls="bdNavbar" aria-expanded="false">
            <span class="navbar-toggler-icon visually-hidden">Menu</span>
            <i class="fa-solid fa-bars"></i>
          </button>
      
          <div class="header-bottom offcanvas offcanvas-end" id="bdNavbar" aria-labelledby="bdNavbarOffcanvasLabel">

          <div class="offcanvas-header px-4 pb-0">
            <button type="button" class="btn-close btn-close-black mt-2" data-bs-dismiss="offcanvas"
              aria-label="Close"></button>
          </div>
          <div class="offcanvas-body align-items-center justify-content-end">
            <ul class="navbar-nav align-items-center mb-2 mb-lg-0">
              <li class="nav-item px-3">
                <a class="nav-link active p-0" aria-current="page" href="{{ url_for('views.index') }}">Home</a>
              </li>
              {% if current_user.is_authenticated %}
              <li class="nav-item px-3">
                <a class="nav-link p-0" href="{{ url_for('views.account', current_user_id=current_user.id) }}">Account</a>
              </li>
              <li class="nav-item px-3">
                <a class="nav-link p-0" href="{{ url_for('views.logout') }}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item px-3">
                <a class="nav-link p-0" href="{{ url_for('views.login') }}">Login</a>
              </li>
              <li class="nav-item px-3">
                <a class="nav-link p-0" href="{{ url_for('views.register') }}">Register</a>
              </li>
              {% endif %}
              <li class="nav-item px-3">
                <a class="nav-link p-0" href="{{ url_for('views.index') }}">Resources</a>
              </li>
              <li class="nav-item px-3">
                <a class="nav-link p-0" href="{{ url_for('views.index') }}">Highlights</a>
              </li>
              <li class="nav-item px-3">
                <a class="nav-link p-0" href="{{ url_for('views.about') }}">About</a>
              </li>
              <li class="nav-item px-3">
                <a class="nav-link p-0" href="{{ url_for('views.submit_resource') }}">Submit a Resource</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <!-- Sub-header: placed BELOW primary header and NOT fixed -->
    <nav class="sub-header" aria-label="secondary header">
      <div class="container sub-header-content">
        <div class="left-info d-flex align-items-center">
          <span class="d-flex align-items-center">
            <i class="fa-solid fa-location-dot sub-icon" aria-hidden="true"></i>
            <span class="sub-text">Redmond, Washington</span>
          </span>
          <span class="d-flex align-items-center ms-3">
            <i class="fa-solid fa-phone sub-icon" aria-hidden="true"></i>
            <span class="sub-text">+### ### ####</span>
          </span>
          <span class="d-flex align-items-center ms-3">
            <i class="fa-regular fa-clock sub-icon" aria-hidden="true"></i>
            <span class="sub-text">24/7, Monday–Sunday</span>
          </span>
        </div>

        <div class="right-links d-flex align-items-center">
          <a class="github-link d-flex align-items-center" href="https://github.com/AnishVDev/TSA-WEBMASTER" target="_blank"
            rel="noopener">
            <i class="fa-brands fa-github sub-icon"></i>
            <span class="sub-text ms-1">View on GitHub</span>
          </a>
        </div>
      </div>
    </nav>
  </header>
  {% block content %}

  {% endblock %}
  <footer>
    <p>© 2025 Community Resource Hub | TSA Webmaster </p>
  </footer>

  <!-- Bootstrap JS (includes offcanvas) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

  <script>
    // Toggle scrolled class on primary header (used for subtle background change)
    window.addEventListener("scroll", function () {
      const header = document.getElementById("primary-header");
      if (!header) return;
      if (window.scrollY > 50) {
        header.classList.add("scrolled");
      } else {
        header.classList.remove("scrolled");
      }
    });

    // Resource search and filter
    const search = document.getElementById("search");
    const categoryFilter = document.getElementById("categoryFilter");
    const cards = document.querySelectorAll("#resourceList .card");

    function filterResources() {
      const searchTerm = (search?.value || "").toLowerCase();
      const category = categoryFilter?.value || "all";

      cards.forEach(card => {
        const text = card.textContent.toLowerCase();
        const cardCategory = card.getAttribute("data-category");
        const matchesSearch = text.includes(searchTerm);
        const matchesCategory = category === "all" || cardCategory === category;

        card.style.display = matchesSearch && matchesCategory ? "block" : "none";
      });
    }

    if (search) search.addEventListener("input", filterResources);
    if (categoryFilter) categoryFilter.addEventListener("change", filterResources);

    // Submit form
    const form = document.getElementById("resourceForm");
    const message = document.getElementById("formMessage");
    if (form) {
      form.addEventListener("submit", e => {
        e.preventDefault();
        message.textContent = "Thank you! Your resource has been submitted.";
        form.reset();
        // TODO: integrate real backend / storage
      });
    }
  </script>
</body>
</html>

tsa_webmaster/templates/error.html
{% extends 'base.html' %}
<!-- Error page for when an error occurs -->
{% block content %}
<div class="container">
    <h1>Error</h1>
    <p>{{ error }}</p>
</div>
{% endblock %}

tsa_webmaster/templates/index.html
{% extends 'base.html' %}
{% block content %}
  <main>
    <!-- If the user is redirected to the home page from a different page, show a flashed message -->
    {% if indexmessage == "login" %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>You're logged in!</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif indexmessage == "submit" %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Resource submitted!</strong> Thanks for your submission!
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif indexmessage == "logout" %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Successfully logged out!</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif indexmessage == "resource" %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Resource not found!</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% elif indexmessage == "account" %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Account not found!</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% elif indexmessage == "delete" %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Resource deleted!</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}

    <section id="home" class="hero">
      <div class="container hero-inner">
        <div class="hero-text">
          <h2>Connecting People with Local Support, Events, and Opportunities</h2>
          <p>Discover, share, and connect with your community’s resources.</p>
          <div class="hero-cta">
            <a href="#resources" class="btn">Explore Resources</a>
            <a href="#submit" class="btn btn-outline">Submit a Resource</a>
          </div>
        </div>
        
        <div class="hero-features">
          <div class="feature">
            <i class="fa-solid fa-magnifying-glass"></i>
            <h4>Searchable Directory</h4>
            <p>Find services near you by category, distance, and hours.</p>
          </div>
          <div class="feature">
            <i class="fa-solid fa-calendar-days"></i>
            <h4>Local Events</h4>
            <p>Discover nearby community events and volunteer opportunities.</p>
          </div>
          <div class="feature">
            <i class="fa-solid fa-hand-holding-heart"></i>
            <h4>Trusted Support</h4>
            <p>Community-verified resources and contact information.</p>
          </div>
        </div>
      </div>
    </section>

    <!-- rest of page remains unchanged -->
    <section id="highlights" class="container">
      <h2>Featured Community Highlights</h2>
      <div class="card-grid">
        <div class="card">
          <h3>Resource Highlight 1</h3>
          <p>Placeholder description for a featured local resource.</p>
          <a href="#" class="btn">Learn More</a>
        </div>
        <div class="card">
          <h3>Resource Highlight 2</h3>
          <p>Placeholder description for another featured service.</p>
          <a href="#" class="btn">Learn More</a>
        </div>
        <div class="card">
          <h3>Resource Highlight 3</h3>
          <p>Placeholder description for a third local resource.</p>
          <a href="#" class="btn">Learn More</a>
        </div>
      </div>
    </section>

    <section id="resources" class="container">
      <h2>Resource Hub Directory</h2>
      <input type="text" id="search" placeholder="Search resources..." />

      <div class="filter">
        <select id="categoryFilter">
          <option value="all">All Categories</option>
          <option value="volunteering">Volunteering</option>
          <option value="education">Education</option>
          <option value="recreation">Recreation</option>
          <option value="misc">Miscellaneous</option>
        </select>
      </div>

      <div id="resourceList" class="card-grid">
        <!-- Resources -->
         {% for resource in resources %}
        <div class="card" data-category="{{ resource.resource_category }}">
          <h3>{{ resource.resource_title }}</h3>
          <p>Created by: {{ resource.author.username }}</p>
          <p>Created on: {{ resource.created_date.strftime('%Y-%m-%d') }}</p>
          <p>Category: {{ resource.resource_category }}</p>
          <p>Tags: {{ resource.resource_tags }}</p>
          <p class="truncate">Description: {{ resource.resource_description }}</p>
          <p>Location: {{ resource.resource_location }}</p>
          <p>Date: {{ resource.resource_date.strftime('%Y-%m-%d') }}</p>
          <p>Time: {{ resource.resource_time.strftime('%H:%M') }}</p>
          <a href="{{ url_for('views.resource', resource_id=resource.id) }}" class="btn">Learn More</a>
        </div>
        {% endfor %}
      </div>
    </section>

    <section id="submit" class="container">
      <h2>Submit a New Resource</h2>
      <form id="resourceForm">
        <label for="name">Resource Name</label>
        <input type="text" id="name" required>

        <label for="description">Description</label>
        <textarea id="description" required></textarea>

        <label for="category">Category</label>
        <select id="category" required>
          <option value="">Select a Category</option>
          <option value="volunteering">Volunteering</option>
          <option value="education">Education</option>
          <option value="recreation">Recreation</option>
          <option value="misc">Miscellaneous</option>
        </select>

        <label for="contact">Contact Info</label>
        <input type="text" id="contact" required>

        <button type="submit" class="btn">Submit Resource</button>
      </form>
      <p id="formMessage"></p>
    </section>

    <section id="about" class="container">
      <h2>About This Project</h2>
      <p>
        We are the greatest TSA team!!!!!! We are the greatest!
      </p>
    </section>
  </main>
{% endblock %}

tsa_webmaster/templates/login.html
{% extends 'base.html' %}
{% block content %}
<!-- If the user is redirected to the login page from a different page, or if they put an invalid email or password, show a flashed message -->
{% if loginmessage == "register" %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Thanks for Signing Up!</strong> Please login to continue.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% elif loginmessage == "submit" %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Please login first!</strong> You must be logged in to submit a resource.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% elif loginmessage == "attend" %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Please login first!</strong> You must be logged in to attend a resource.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% elif loginmessage == "unattend" %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Please login first!</strong> You must be logged in to unattend a resource.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% elif loginmessage == "invalid" %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Invalid username or password.</strong> Please try again.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endif %}
<!-- Login form -->
<div class="container mt-4 p-5 bg-primary text-dark rounded">
    <h1>Login</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label }} {{ form.email(class='form-control') }}
        {{ form.password.label }} {{ form.password(class='form-control') }}
        {{ form.submit(class='btn btn-primary') }}
    </form>
</div>
{% endblock %}

tsa_webmaster/templates/register.html
{% extends 'base.html' %}
{% block content %}
<!-- Registration form -->
<div class="container mt-4 p-5 bg-primary text-dark rounded">
    <h1>Register</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label }} {{ form.email(class='form-control') }}
        {{ form.username.label }} {{ form.username(class='form-control') }}
        {{ form.password.label }} {{ form.password(class='form-control') }}
        {{ form.confirm_password.label }} {{ form.confirm_password(class='form-control') }}
        {{ form.submit(class='btn btn-primary') }}
    </form>
</div>
{% endblock %}

tsa_webmaster/templates/resource.html
{% extends 'base.html' %}
{% block content %}
<!-- If the user reaches a resource's page from a different page, show a flashed message -->
{% if resourcemessage == "delete" %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>You are not authorized to delete this resource.</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% elif resourcemessage == "attend" %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Congratulations!</strong> You are now attending this resource.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% elif resourcemessage == "unattend" %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>You are no longer attending this resource.</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% elif resourcemessage == "already_attending" %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>You're already attending this resource.</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% elif resourcemessage == "not_attending" %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>You cannot unattend a resource you're not attending.</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% elif resourcemessage == "already_created" %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>You created this resource!</strong> You are attending it.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
<!-- Resource description page-->
<div class="container mt-4 p-5 bg-primary text-dark rounded">
    <h1>{{ resource.resource_title }}</h1>
    <p>Created by: {{ resource.author.username }}</p>
    <p>Created on: {{ resource.created_date.strftime('%Y-%m-%d') }}</p>
    <p>Category: {{ resource.resource_category }}</p>
    <p>Tags: {{ resource.resource_tags }}</p>
    <p>Description: {{ resource.resource_description }}</p>
    <p>Location: {{ resource.resource_location }}</p>
    <p>Date: {{ resource.resource_date.strftime('%Y-%m-%d') }}</p>
    <p>Time: {{ resource.resource_time.strftime('%H:%M') }}</p>
    {% if current_user.is_authenticated and current_user.id == resource.user_id %}
    <a href="#" class="btn btn-primary">Edit</a>
    <a href="{{ url_for('views.delete', resource_id = resource.id) }}" class="btn btn-danger">Delete</a>
    {% endif %}
    {% if current_user.is_authenticated%}
            {% if current_user.id != resource.user_id %}
                {% if is_attending == False %}
                <a href="{{ url_for('views.attend', resource_id = resource.id) }}" class="btn btn-success">Attend</a>
                {% else %}
                <a href="{{ url_for('views.unattend', resource_id = resource.id) }}" class="btn btn-danger">Unattend</a>
                {% endif %}
            {% else %}
            <p><strong>You created this resource!</strong></p>
            {% endif %}
    {% else %}
    <a href="{{ url_for('views.login') }}" class="btn btn-success">Login to Attend</a>
    {% endif %}
    <h2>Attendees</h2>
    {% if resource.attendees and resource.attendees|length > 0 %}
    <ul>
        {% for attendee in resource.attendees %}
        <li>{{ attendee.attendee.username }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No attendees yet.</p>
    {% endif %}
</div>
{% endblock %}